#Para conectar, poner en el localhost db
version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  db:
