version: "3.8"
services:
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 8001:8001
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge
