version: "3.8"
services:
  redis:
    image: redis
    command: redis-server --requirepass root --save 60 1 --loglevel warning
    ports:
      - 60045:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: root
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge